### ISSUE TITLE
Tabs opened are not formatted on save

### ISSUE THREAD

**Issue by isaacsanders** [mhinz/vim-mix-format#10]
Hey all,

I appreciate the work on this.

I have encountered an issue when I open a file, then open another file with `:tabe`.

The first file is formatted on save when I have the appropriate variable set.

The second file produces an error message. It still formats the file, but this error opens a scratch buffer unless errors are silenced. Then it just blinks a disconcerting red spot at the bottom of my screen.

**Comment by mhinz** [comment]
Hi,

1. What is the error message? Is there something suspicious in `:messages`? No idea what a red blinking is supposed to mean.
2. What are the exact steps to reproduce it?

    I tried this to no avail:

    ```
    $ vim one.exs
    :w
    :tabe two.exs
    :w
    gt
    u
    :w
    ```

    Works without problems here.
3. What Vim version do you use?
4. Could you try disabling as many other plugins as possible? Often they interfere in unexpected ways, so it's good to disable them in the meanwhile.

**Comment by isaacsanders** [comment]
`Formatting failed. Check :messages.`

It isn't weird red stuff, it is just the normal red of a Error being logged, but `:messages` is empty.

**Comment by isaacsanders** [comment]
I am on vim 8.0

**Comment by isaacsanders** [comment]
It also takes the unsaved buffers I have and reformats the last saved version and replaces my changes with the formatted version of the previously saved file.

**Comment by mhinz** [comment]
Huh, I can reproduce it with Vim but not with Neovim.

Thanks, I'm looking into it.

**Comment by mhinz** [comment]
Okay, it should be fixed on master!

It was a rather stupid issue and led to an autocmd set twice, so.. basically the plugin was run twice on `:w`, one time succeeding and one time failing. And Neovim is simply handling it better than Vim.

Anyway, the autocmd is only set once now and it should work the same everywhere.

**Comment by mhinz** [comment]
I'm pretty sure it's fixed now, so I'm closing this. (Please reopen this issue otherwise.)

Thanks for bringing this up! ✨

**Comment by isaacsanders** [comment]
Sounds good. I appreciate it. I have been using it the past few days, and it seems to be working great.

I may have found another bug, but I haven't put together a set of retro steps yet. so I will take care of that soon.

Thanks for this project.
