### ISSUE TITLE
folds collapse when saved

### ISSUE THREAD

**Issue by dustinfarris** [mhinz/vim-mix-format#12]
When i have it set to run automatically on save, my open folds collapse every time I save.  Is there a way to keep it from doing that?

**Comment by mhinz** [comment]
I don't know anything about your fold settings, but I guess the same happens if you simply do `:e!`?

**Comment by dustinfarris** [comment]
Yes, that's correct.

Also, (this might be a separate issue), if I'm jumping around panes, I noticed that the MixFormat saves the pane I have in focus after the format operation is done.  This is causing issues with NerdTree.
-- 
Dustin Farris

**Comment by mhinz** [comment]
Both issues should now be addressed on master!

**Comment by mhinz** [comment]
I was able to reproduce both issues you mentioned and the above two commits fixed them for me.

I consider this solved, so I'm closing this. Please reopen if you still experience any issues.
