### ISSUE TITLE
`:MixFormat` discards undo history

### ISSUE THREAD

**Issue by nathanl** [mhinz/vim-mix-format#13]
Great plugin! Really handy, thanks for building it.

My issue: when I run `:MixFormat`, my undo history is lost. Is there a way to prevent this?

I'm using Vim 8.0.

**Comment by mhinz** [comment]
> Great plugin! Really handy, thanks for building it.

Thanks!

> My issue: when I run :MixFormat, my undo history is lost.

Usually that shouldn't happen, so I started investigating.. and fortunately your dotfiles are on GitHub as well. That led me to [this line](https://github.com/nathanl/.dotfiles/blob/master/vim/vimrc#L26) which is unusual (at least I didn't see people using that very often) but legit. :-)

The above commit should now preserve the undo history in your case.

**Comment by nathanl** [comment]
😲 ❤️ ❤️ 🔥 😄 😄 😄 👍 👍 !!!!

You... figured out the problem with *my dotfiles* and adjusted *your library* to deal with *my weirdness*, like 3 hours after I opened my issue!

That... is epic. There is no way that I have any right to expect an open source author to do - well, anything, really, but especially not that kind of custom free work.

Can... can I tip you or something?

**Comment by mhinz** [comment]
Hah, thanks! :)

It's really just the experience of writing and maintaining many, more or less popular, Vim plugins for years already. Given enough info in the bug report, I usually can make good enough guesses to quickly find the issue.

> can I tip you or something?

I appreciate the gesture! But I don't take any money for my OSS work. People helping me to make the code more robust is good enough for me. (And maybe starring the repo. ;-))

But thanks again!
