### ISSUE TITLE
Open :messages in quickfix by default

### ISSUE THREAD

**Issue by wcpines** [mhinz/vim-mix-format#14]
When not silencing the mix format errors, it would be nice if the errors populated the quickfix, as opposed to a buffer/window.  It makes buffer and window navigation behave a bit oddly.

**Comment by wcpines** [comment]
Alt: if the buffer were to be deleted (`:bd!`) when the corresponding messages window is closed, that works too. I'm not sure which is easier.  (My apologies: I'm pretty awful at groking vimscript).

**Comment by mhinz** [comment]
You're totally right. I can't really recall why I didn't do this in the first place, but using a location list is certainly the most vim-like solution.

I'll hack something up!

**Comment by mhinz** [comment]
Should work now! Thanks for bringing this up. ✨

**Comment by mhinz** [comment]
Just one thing.. assuming the following stacktrace:

```
** (SyntaxError) example.ex:3: syntax error before: '.'
    (elixir) lib/code.ex:538: Code.format_string!/2
    (mix) lib/mix/tasks/format.ex:397: Mix.Tasks.Format.format_file/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

The qf list is populated only with the line beginning with `**`, which contains the actual error. How useful is the rest of the stacktrace to you? I think it could be added as non-navigatable info to the quickfix list, but I'm not sure whether that's useful or not.

Now, it looks just like this:

```
example.ex|3| syntax error before: '.'
```

But I could make it like this:

```
example.ex|3| syntax error before: '.'
||    (elixir) lib/code.ex:538: Code.format_string!/2
||    (mix) lib/mix/tasks/format.ex:397: Mix.Tasks.Format.format_file/2
||    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
||    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
||    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

In Vim terms that would still be a single error, but with follow-up information. But these stacktraces can get long quickly, so I decided against it unless someone else has good arguments for it.

**Comment by wcpines** [comment]
@mhinz thanks so much for the detailed follow up :D.  

I tried out the updated version briefly, and it appears that the formatter only shows one error at a time. Since that's the case, I think including the full stack trace would be great. I like having the context, and it doesn't seem to reduce usability. 
Also, my QF window is set to a certain height, but if I need to view a longer message, I can easily toggle the window to full screen using something like `troydm/zoomwintab.vim`. 

Thoughts?

**Comment by mhinz** [comment]
> I tried out the updated version briefly, and it appears that the formatter only shows one error at a time. Since that's the case, I think including the full stack trace would be great. I like having the context, and it doesn't seem to reduce usability.

Well, I agree! Let's just roll with it.
