### ISSUE TITLE
Command is not available

### ISSUE THREAD

**Issue by adamu** [mhinz/vim-mix-format#16]
Hello, I'm not sure if this is a problem with my environment, but after installing this plugin, the `:MixFormat` command is not available in vim. I am using the dein plugin manager with vim 8.0.596 on OSX.

Steps followed:

1. Added to `.vimrc`:
`call dein#add('mhinz/vim-mix-format')`
2. Confirmed module was installed:
```
[dein] Not installed plugins: ['vim-mix-format']
[dein] Update started: (2018/11/25 16:16:14)
[dein] (1/1) |vim-mix-format      | git clone --recursive https://github.com/mhinz/vim-mix-format.git "/Users/adam/.vim/dein/repos/github.com/mhinz/vim-mix-format"
[dein] (1/1) [====================] vim-mix-format
[dein] (1/1) |vim-mix-format      | Updated
[dein] (1/1)  -> ee602a459eea767b3aabc2d0061616146fe2a5f2
[dein] Updated plugins:
[dein]   vim-mix-format(1 change)
[dein] Done: (2018/11/25 16:16:16)
```

3. `:MixFormat` is not available.
`E492: Not an editor command: MixFormat`

I've also comfimed `mix format $file` works on the command line.

**Comment by mhinz** [comment]
Either you're not in an Elixir file (`:set ft=elixir`) or there is a problem with the plugin manager (check if `:scriptnames` shows the plugin as sourced).

**Comment by adamu** [comment]
Thanks. It seems to be conflicting with the `elixir-lang/vim-elixir` plugin.

Using `:scriptnames`, I found `~/.vim/dein/.cache/.vimrc/.dein/ftplugin/elixir.vim`

If I enable `vim-elixir`, then the contents of the above `elixir.vim` file seems to contain code for `vim-elixir`, but if I disable it, then the same file seems to have the relevant code required for `vim-mix-format` (and `:MixFormat` works).

I have them both working together on another machine, I'll check it tomorrow and see if I can find any difference to my current setup here. I'm wondering if dein just copies all the plugin scripts to the `ftplugin` in the cache directory, in this case it looks like `vim-elixir` always wins, regardless of the order I install them.

**Comment by mhinz** [comment]
Oh, I see. Both, `vim-elixir` and `vim-mix-format` have a file `ftplugin/elixir.vim` and the dein cache just copies one over the other. That's bad. :>

I never used dein, but there are many filetype-specific plugins out there that use `ftplugin/<filetype>.vim`, so there is surely a way around that.

I'm closing this since it's clearly not an issue of this plugin, but please report back anyway. There might be other people having the same issue in the future. :)

**Comment by adamu** [comment]
I found https://github.com/Shougo/dein.vim/issues/153

It's a bit obscure, but the official method is to add `{'merged': 0}` to the conflicting plugin.

```vim
call dein#add('elixir-lang/vim-elixir')
call dein#add('mhinz/vim-mix-format', {'merged': 0})
```
