### ISSUE TITLE
breaks when editing a file outside the current directory when import_deps is used

### ISSUE THREAD

**Issue by notslang** [mhinz/vim-mix-format#21]
If I attempt to edit a file from a project when I have not `cd`'d into the directory of the project before opening vim, then mix format will fail to run.

For example, if I open up a random file from my home directory with `vim proj/msoe/about-time-2/api-server/mix.exs` and save it then I will get the message "Formatting failed."

Running `:verb MixFormat` shows that this is the command that gets run:

```
MixFormat: ['env', '-u', 'MIX_ENV', 'sh', '-c', 'mix format --check-equivalent --dot-formatter ''/
data/proj/msoe/about-time-2/api-server/.formatter.exs'' ''/data/proj/msoe/about-time-2/api-server/
mix.exs''']
```

If I run that command manually in the shell then I get this error:

```
$ mix format --check-equivalent --dot-formatter '/data/proj/msoe/about-time-2/api-server/.formatter.exs' '/data/proj/msoe/about-time-2/api-server/mix.exs'
** (Mix) Unknown dependency :ecto given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :dev
```

I assume that `mix format` is trying to import dependencies in the current directory, rather than the directory that the file being formatted is in.

This is my `.formatter.exs` at `proj/msoe/about-time-2/api-server/.formatter.exs`:

```elixir
[
  import_deps: [:ecto, :phoenix],
  inputs: ["{mix,.formatter}.exs", "{config,lib,priv,test}/**/*.{ex,exs}"]
]
```

**Comment by mhinz** [comment]
Okay, I can reproduce this. Will try to fix it this weekend!

**Comment by mhinz** [comment]
This should be fixed now. We now always change to the root directory of the mix project temporarily before running `mix format`.

Thanks for reporting this! ✨

**Comment by notslang** [comment]
It works! Thanks!
