### ISSUE TITLE
Swap file stays after :wq

### ISSUE THREAD

**Issue by UlisseMini** [mhinz/vim-mix-format#23]
## Minimal config needed to reproduce
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'mhinz/vim-mix-format'
call plug#end()

au BufReadPost *.ex set filetype=elixir
let g:mix_format_on_save = 1
```

## Neovim version
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

## How to reproduce
Put my minimal config into `elixir.vim` and run `nvim test.ex -u elixir.vim`
Insert some elixir code and :wq a bunch (make sure its actually formatting)

## Actual swap file error
```
E325: ATTENTION
Found a swap file by the name "~/.local/share/nvim/swap//%home%peep%.config%nvim%ftplugin%test.ex.swp"
          owned by: peep   dated: Tue Apr 30 21:18:49 2019
         file name: ~peep/.config/nvim/ftplugin/test.ex
          modified: no
         user name: peep   host name: core
        process ID: 8395
While opening file "test.ex"
             dated: Tue Apr 30 21:18:49 2019

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r test.ex"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/home/peep/.local/share/nvim/swap//%home%peep%.config%nvim%ftplugin%test.ex.swp"
    to avoid this message.

Swap file "~/.local/share/nvim/swap//%home%peep%.config%nvim%ftplugin%test.ex.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort:
```
When checking, that process is not running on my system and i continue to get the error. i fixed it in this case with `rm ~/.local/share/nvim/swap//%home%peep%.config%nvim%ftplugin%test.ex.swp`

EDIT: Was able to reproduce without `elixir-editors/vim-elixir`

**Comment by mhinz** [comment]
That's a bug in the latest Nvim release which is already fixed on master. But I found that the above workaround works for releases up to 3.5! :+1:

**Comment by rlefevre** [comment]
I still have the issue with Neovim 0.3.8 (stable ppa for Ubuntu) when using `:wq`.

> That's a bug in the latest Nvim release which is already fixed on master. 

What is the reference of the bug? I would like to know from which version it is included.

> But I found that the above workaround works for releases up to 3.5! +1

What is the work-around? I only see deleting the `.swp` file, but this is not really a work-around as this must be done each time the file is edited after nvim has been exited.

**Edit:**
I updated to Neovim 0.5.0 from unstable ppa. The `swp` file issue does not occur anymore, but I get the following message on `:wq`, even for valid elixir source files:
```
Formatting failed. Check :messages.
```
