### ISSUE TITLE
The window scrolls after format

### ISSUE THREAD

**Issue by darkbaby123** [mhinz/vim-mix-format#28]
I use NeoVim 0.3.8. After each format the cursor stays the same, but the window scrolls to center the cursor vertically (like I press `z.`). I don't know if it's an expected behaviour or not for this plugin, but most other editors doesn't behaves this way.

**Comment by mhinz** [comment]
Yup, that's a side effect of using `:edit` for "reloading" the current buffer.

Should be fixed now!
