### ISSUE TITLE
Neovim folding issue

### ISSUE THREAD

**Issue by npearson72** [mhinz/vim-mix-format#34]
This is probably an issue in standard vim too.

Seems that `MixFormat` clobbers any existing folds that are in the buffer.

Anyway to prevent it from doing that?

**Comment by dinocosta** [comment]
Hi @npearson72 , if your problem has to do with folds coming undone after running `:MixFormat` I've worked on a change for it → https://github.com/mhinz/vim-mix-format/pull/36 .

If you want you can give it a go and let me know if that fixes it for you 👍

**Comment by mhinz** [comment]
Yup, that patch got merged and folds should be working now!
