### ISSUE TITLE
Print syntax errors 

### ISSUE THREAD

**Issue by wcpines** [mhinz/vim-mix-format#4]
**TL;DR:** Printing complete stacktrace/error when formatter fails would be tight. ✨ 

When running `:MixFormat` on a file that contains syntax errors, the error reported [by neovim in my case] appears to be the final error in the stack:

```sh
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Running `mix formt [FILE]` from a shell window reports:

```
mix format failed for file: [FILE].exs

** (SyntaxError) [FILE].exs:30: "(" is missing terminator ")". unexpected token: "end" at line 44
    (elixir) lib/code.ex:443: Code.format_string!/2
    (mix) lib/mix/tasks/format.ex:281: Mix.Tasks.Format.format_file/3
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
I'd love to se that missing terminator error printed in vim!

**Comment by mhinz** [comment]
That only happens because Vim redraws the screen (it does so in all kinds of situations and is hard to avoid) which makes all earlier lines disappear.

`:messages` should show everything!

**Comment by mhinz** [comment]
Okay.. now we echo the error _twice_. First using `:echomsg`, which also logs to the message history, and using `:echo`, which doesn't log to the message history and overwrites the output of `:echomsg`..

This sounds weird, but does what we want.. we get the full error right away on `:MixFormat` and can still look it up later with `:messages`.

Thanks for bringing this up! :+1:

**Comment by mhinz** [comment]
Actually.. it will only work in Neovim, because Vim is buggy:

```
:call job_start('true', {'exit_cb': {-> execute('echo "foo\nbar", '')}})
```

This should output 2 lines, but outputs _nothing_...

UPDATE: I sent an issue report to the Vim project. Hopefully they'll fix this.

**Comment by wcpines** [comment]
I do use neovim (I should have been specific, sorry) so it sounds like I have a way to get what I want:

`:MixFormat` then `:messages` then `G` to scroll to bottom.  

Something less manual would be amazing, but I understand if this isn't exactly an urgent feature. 

Thanks for the work on this, loving it so far!  Especially since I'm still learning syntax/style of elixir.

**Comment by mhinz** [comment]
> I do use neovim (I should have been specific, sorry)

I know! You said that in the first post. :-)

Did you update the plugin? The latest version should show the whole error on Neovim right away (without using `:messages`).

**Comment by wcpines** [comment]
(🤦‍♂️   Should have re-read my own post/had more faith in my issue reporting)  

Just updated, and very stoked.  Thank you!

**Comment by mhinz** [comment]
Quick update:

As mentioned above, echoing is handled differently in Vim and Neovim and that won't change in the future. Thus I decided to change the way errors are displayed.

Now a new window is opened instead, which works the same for Vim and Neovim.
