### ISSUE TITLE
Use --check-equivalent when formatting

### ISSUE THREAD

**Issue by stevedomin** [mhinz/vim-mix-format#6]
Hello @mhinz,

Thanks for writing this vim extension.

Should the extension use the `--check-equivalent` option when calling `mix format`?

The docs recommend to use it when automatically formatting files: https://hexdocs.pm/mix/Mix.Tasks.Format.html#module-task-specific-options

**Comment by mhinz** [comment]
I introduced a new option `g:mix_format_options` which defaults to `--check-equivalent`.

Thanks for bringing this up! ✨

**Comment by stevedomin** [comment]
Thanks for fixing it so quickly @mhinz!
