### ISSUE TITLE
formatting an unsaved buffer will lose the last edits without a warning

### ISSUE THREAD

**Issue by flaviogrossi** [mhinz/vim-mix-format#8]
Hi and thanks for this nice plugin.

When executing `:MixFormat` on an unsaved buffer your last edits will be lost without any warning.
Would it be possible to show a warning or to refuse to operate on unsaved buffers?

Thanks

**Comment by mhinz** [comment]
Hi!

It now refuses to act on unsaved buffers and issues a warning message.

Thanks for bringing this up! ✨
